name = "iipython-status-page"
main = "fetch_status.js"
compatibility_date = "2024-09-28"

# Fuck off Cloudflare
workers_dev = false
send_metrics = false

# Force enable keeping logs
[observability]
enabled = true

# Fetch data every hour
[triggers]
crons = ["*/15 * * * *"]

# Setup KV
[[kv_namespaces]]
binding = "statuspage_data"
id = "cdec5b397e54472388031b13783de58e"